# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-25 17:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinica_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cajaingreso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni_c', models.CharField(blank=True, max_length=350, null=True)),
                ('direccion', models.CharField(blank=True, max_length=50, null=True)),
                ('monto', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True, null=True)),
                ('estado_caja', models.IntegerField(choices=[(0, 'New'), (1, 'Anulado'), (2, 'Done'), (3, 'Contab')], default=2)),
            ],
            options={
                'verbose_name': 'Cajaingreso',
                'verbose_name_plural': 'Cajaingresos',
            },
        ),
        migrations.CreateModel(
            name='Citahistorial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serie', models.CharField(blank=True, max_length=350, null=True)),
                ('fecha_atencion', models.DateTimeField(auto_now_add=True, null=True)),
                ('fecha_atender', models.DateTimeField(blank=True, null=True)),
                ('descripcion', models.TextField(blank=True, max_length=350, null=True)),
                ('precio_un', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cantidad', models.IntegerField(blank=True, default=0)),
            ],
            options={
                'verbose_name': 'Citahistorial',
                'verbose_name_plural': 'Citahistorials',
            },
        ),
        migrations.CreateModel(
            name='Citainscripcion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serie', models.CharField(blank=True, max_length=50, null=True)),
                ('ruc', models.CharField(blank=True, max_length=50, null=True)),
                ('tipo_pago', models.CharField(choices=[('Efectivo', 'Efectivo'), ('Cuotas', 'Cuotas')], default='Efectivo', max_length=10)),
                ('tipodocumento_pago', models.CharField(choices=[('Factura', 'Factura'), ('Boleta', 'Boleta'), ('Ticket', 'Ticket')], default='Ticket', max_length=10)),
                ('direccion', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_citasuscripcion', models.DateTimeField(auto_now_add=True, null=True)),
                ('fecha_citaatencion', models.DateTimeField(blank=True, null=True)),
                ('estado_cita', models.IntegerField(choices=[(0, 'New'), (1, 'Anulado'), (2, 'Done'), (3, 'Contab')], default=2)),
                ('apellidos_c', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clinica_app.Cliente')),
            ],
            options={
                'verbose_name': 'Citainscripcion',
                'verbose_name_plural': 'Citainscripcions',
            },
        ),
        migrations.CreateModel(
            name='Cuentausuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(blank=True, max_length=50, null=True)),
                ('password', models.CharField(blank=True, max_length=20, null=True)),
                ('saldo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('email', models.EmailField(blank=True, max_length=50, null=True)),
                ('fechasuscripcion_usuario', models.DateTimeField(auto_now_add=True, null=True)),
                ('apellidos_cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clinica_app.Cliente')),
            ],
            options={
                'verbose_name': 'Cuentausuario',
                'verbose_name_plural': 'Cuentausuarios',
                'ordering': ['usuario'],
            },
        ),
        migrations.CreateModel(
            name='Especialidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_especialidad', models.CharField(blank=True, max_length=50, null=True)),
                ('descripcion', models.TextField(blank=True, max_length=350, null=True)),
                ('precio_especialidad', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'verbose_name': 'Especialidad',
                'verbose_name_plural': 'Especialidads',
                'ordering': ['nombre_especialidad'],
            },
        ),
        migrations.CreateModel(
            name='Odontologo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apellidos_odontologo', models.CharField(blank=True, max_length=50, null=True)),
                ('nombre_odontologo', models.CharField(blank=True, max_length=50, null=True)),
                ('direccion_odontologo', models.CharField(blank=True, max_length=50, null=True)),
                ('telefono_odontologo', models.CharField(blank=True, max_length=9, null=True)),
                ('tipodoc_odontologo', models.CharField(choices=[('DNI', 'DNI'), ('RUC', 'RUC')], default='DNI', max_length=10)),
                ('numdoc_odontologo', models.IntegerField(blank=True, null=True)),
                ('email_odontologo', models.EmailField(max_length=50, null=True)),
                ('genero_odontologo', models.CharField(choices=[('Hombre', 'Hombre'), ('Mujer', 'Mujer')], default='Hombre', max_length=10)),
            ],
            options={
                'verbose_name': 'Odontologo',
                'verbose_name_plural': 'Odontologos',
                'ordering': ['nombre_odontologo'],
            },
        ),
        migrations.AddField(
            model_name='citainscripcion',
            name='apellidos_o',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clinica_app.Odontologo'),
        ),
        migrations.AddField(
            model_name='citahistorial',
            name='nombree_atencion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clinica_app.Especialidad'),
        ),
        migrations.AddField(
            model_name='citahistorial',
            name='seri',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clinica_app.Citainscripcion'),
        ),
        migrations.AddField(
            model_name='cajaingreso',
            name='cita_se',
            field=models.ManyToManyField(blank=True, null=True, related_name='cita_set', to='clinica_app.Citainscripcion'),
        ),
        migrations.AddField(
            model_name='cajaingreso',
            name='usuar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clinica_app.Cuentausuario'),
        ),
    ]
