# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-25 18:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinica_app', '0003_auto_20170625_1316'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='odontologo',
            options={'ordering': ['apellidos_odontologo'], 'verbose_name': 'Odontologo', 'verbose_name_plural': 'Odontologos'},
        ),
    ]
