# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-25 18:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinica_app', '0004_auto_20170625_1317'),
    ]

    operations = [
        migrations.RenameField(
            model_name='citainscripcion',
            old_name='fecha_citaatencion',
            new_name='fecha_citaatender',
        ),
    ]
