# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-28 23:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinica_app', '0007_remove_cuentausuario_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cuentausuario',
            old_name='apellidos_cliente',
            new_name='apellidos_clien',
        ),
    ]
