# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-30 04:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinica_app', '0010_auto_20170629_2311'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cuentausuario',
            options={'ordering': ['codigo_usuario'], 'verbose_name': 'Cuentausuario', 'verbose_name_plural': 'Cuentausuarios'},
        ),
        migrations.RenameField(
            model_name='cuentausuario',
            old_name='num_cuenta',
            new_name='codigo_usuario',
        ),
    ]
