# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-30 05:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica_app', '0012_auto_20170629_2346'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cajaingreso',
            old_name='dni_c',
            new_name='dni_pagador',
        ),
        migrations.AlterField(
            model_name='cajaingreso',
            name='serie_inscrip',
            field=models.ManyToManyField(blank=True, null=True, related_name='serie_in', to='clinica_app.Citainscripcion'),
        ),
    ]
