# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-30 06:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica_app', '0013_auto_20170630_0012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cajaingreso',
            name='serie_inscrip',
            field=models.ManyToManyField(blank=True, null=True, related_name='serie_i', to='clinica_app.Citainscripcion'),
        ),
    ]
