# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-30 13:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinica_app', '0014_auto_20170630_0144'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='citainscripcion',
            name='estado_cita',
        ),
    ]
